spring.application.name=swipenow
server.address=0.0.0.0
server.port=8081
#server.port=${PORT:8081}


#spring.jpa.hibernate.ddl-auto=update
#
#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE
#spring.datasource.username=c##Swipenow
#spring.datasource.password=swipenow
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
#
#spring.jpa.show-sql=true

server.forward-headers-strategy=framework
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=t20798028@gmail.com
#spring.mail.password=kutwvepnimurrhgz
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true


spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a2f51e001@smtp-brevo.com
#spring.mail.password=xsmtpsib-81fd6deefc7ecfdfec1684eb8432ee92b74cf58535056ff057e8aaa2dfed104d-GplNtG9xQgGVVYd2
#spring.mail.password=xsmtpsib-81fd6deefc7ecfdfec1684eb8432ee92b74cf58535056ff057e8aaa2dfed104d-n00hGilc6MJ6gy3R
spring.mail.password=${BREVOAPIKEY}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



# spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0

# spring.datasource.username=postgres.csuoqebombiuoslzwwys
# spring.datasource.password=swipenow@1307

# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update

# spring.jpa.show-sql=true

# spring.mvc.async.request-timeout=5000

# spring.datasource.hikari.maximum-pool-size=10
# spring.datasource.hikari.minimum-idle=2
# spring.datasource.hikari.auto-commit=false
# spring.datasource.hikari.pool-name=SupabaseHikariPool


# ===============================
# DATABASE (SUPABASE POOLER)
# ===============================

# spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
# spring.datasource.username=postgres.csuoqebombiuoslzwwys
# spring.datasource.password=swipenow@1307
# spring.datasource.driver-class-name=org.postgresql.Driver


# # ===============================
# # HIKARI CONNECTION POOL
# # (optimized for Supabase free tier)
# # ===============================

# spring.datasource.hikari.pool-name=SupabaseHikariPool
# spring.datasource.hikari.maximum-pool-size=5
# spring.datasource.hikari.minimum-idle=1
# spring.datasource.hikari.connection-timeout=30000
# spring.datasource.hikari.idle-timeout=10000
# spring.datasource.hikari.max-lifetime=30000
# spring.datasource.hikari.auto-commit=false

# spring.datasource.hikari.initialization-fail-timeout=60000
# spring.datasource.hikari.connection-timeout=60000
# # ===============================
# # JPA / HIBERNATE
# # ===============================

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=none
# spring.jpa.open-in-view=false
# spring.jpa.show-sql=false


# # ===============================
# # HIBERNATE PERFORMANCE
# # ===============================

# spring.jpa.properties.hibernate.jdbc.batch_size=50
# spring.jpa.properties.hibernate.order_inserts=true
# spring.jpa.properties.hibernate.order_updates=true


# # ===============================
# # SERVER PERFORMANCE
# # ===============================

# spring.mvc.async.request-timeout=5000

# server.compression.enabled=true
# server.compression.mime-types=application/json,text/html,text/xml,text/plain


# # ===============================
# # LOGGING
# # ===============================

# logging.level.org.hibernate.SQL=OFF
# logging.level.com.zaxxer.hikari=INFO


# ===============================
# SERVER
# ===============================



# ===============================
# DATABASE (SUPABASE POOLER)
# ===============================
# ===============================
# DATABASE (SUPABASE POOLER)
# ===============================

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true&prepareThreshold=0
spring.datasource.username=postgres.marjfmmbeuektmtvjkiq
spring.datasource.password=swipenowin@1307
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# HIKARI CONNECTION POOL
# ===============================

spring.datasource.hikari.pool-name=SupabaseHikariPool
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000
spring.datasource.hikari.initialization-fail-timeout=60000
spring.datasource.hikari.auto-commit=false


# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

server.port=${PORT:8080}
server.address=0.0.0.0
# ===============================
# HIBERNATE PERFORMANCE
# ===============================

spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true


# ===============================
# SERVER PERFORMANCE
# ===============================

spring.mvc.async.request-timeout=5000

server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/xml,text/plain


# ===============================
# LOGGING
# ===============================

logging.level.org.hibernate.SQL=OFF
logging.level.com.zaxxer.hikari=INFO



